baseurl = "https://goutamsh.github.io/"
title = "Goutam Shepur"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "goutam"

[params]
    author = "Goutam Shepur"
    info = "Full-Stack Developer"
    description = "Goutam Shepur's personal website"
    avatarurl = "images/avatar.jpg"
    footercontent = ""

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    
    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []
    
    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/goutamsh"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/sh_goutam"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/goutamsh"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 5
    url = "https://medium.com/@goutam.s.h"


# Menu links
[[menu.main]]
name = "About"
weight = 1
url = "/about/"

[[menu.main]]
name = "Blog"
weight = 2
url = "/posts/"

[[menu.main]]
name = "Projects"
weight = 3
url = "/projects/"

[[menu.main]]
name = "Contact me"
weight = 5
url = "/contact/"
